### ISSUE TITLE
OSX Yosemite 10.10.1 error

### ISSUE THREAD

**Issue by bahtou** [glennw/servo-shell#3]
Not really sure where to start.  I just wanted to play with this and out popped this error when I tried to type something in the URL bar

thread 'ScriptTask' panicked at 'assertion failed: begin <= end', /Users/larsberg/rust/src/libcore/str/mod.rs:1475
stack backtrace:
   1:        0x10e98185d - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10e9958dd - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10e961c19 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10e96209e - rt::unwind::begin_unwind_fmt::hce9ab1c081fbc798S9I
   5:        0x10e99516d - rust_begin_unwind
   6:        0x10e9b7e25 - panicking::panic_fmt::hc7d3b6a3960519fdHZs
   7:        0x10e9b74f7 - panicking::panic::h4158d1652bbc7938TXs
   8:        0x10e9bbc66 - str::str.StrExt::slice_chars::hfbe4201bc00c9f08HgA
   9:        0x10e20afd7 - textinput::TextInput::replace_selection::hb87f087ba36f4a92cdz
  10:        0x10e1359bd - textinput::TextInput::handle_keydown::h4df260485cbbd4d7inz
  11:        0x10e13526b - dom::htmlinputelement::JSRef<'a, HTMLInputElement>.VirtualMethods::handle_event::hff2576829e309bd4f6i
  12:        0x10e11c49d - dom::eventdispatcher::dispatch_event::h41b7d6aae674c791WYc
  13:        0x10e0e83f1 - dom::document::JSRef<'a, Document>.DocumentHelpers<'a>::dispatch_key_event::hb69644ba2ce2bbeaPA8
  14:        0x10e1df45f - script_task::ScriptTask::handle_event::h6dbf60e42d8994304oy
  15:        0x10e1ee5c5 - script_task::ScriptTask::handle_msg_from_constellation::h2e646d103cef8957aNx
  16:        0x10e1d8e74 - script_task::ScriptTask::handle_msgs::hd41c68dd683c3bcdSFx
  17:        0x10e1d2877 - script_task::ScriptTask::start::h5afb8ca3da96f1dbIFx
  18:        0x10dcabbf2 - thunk::F.Invoke<A, R>::invoke::h13147721779896093241
  19:        0x10dc7acaf - rt::unwind::try::try_fn::h14697338781292147106
  20:        0x10e997928 - rust_try_inner
  21:        0x10e997915 - rust_try
  22:        0x10dc7b4d3 - thunk::F.Invoke<A, R>::invoke::h1803073708590684298
  23:        0x10e984752 - sys::thread::thread_start::hc1f580397175540a22E
  24:     0x7fff901712fb - _pthread_body
  25:     0x7fff90171278 - _pthread_start
PaintTask: Saw ExitMsg, 4 buffers in use
thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/larsberg/rust/src/libcore/result.rs:PaintTask: Saw ExitMsg, 4 buffers in use
744
stack backtrace:
PaintTask: Saw ExitMsg, 4 buffers in use
PaintTask: Saw ExitMsg, 4 buffers in use
   1:        0x10e98185d - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10e9958dd - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10e961c19 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10e96209e - rt::unwind::begin_unwind_fmt::hce9ab1c081fbc798S9I
   5:        0x10e99516d - rust_begin_unwind
   6:        0x10e9b7e25 - panicking::panic_fmt::hc7d3b6a3960519fdHZs
   7:        0x10deb9433 - pipeline::Pipeline::force_exit::h6599ac8e670767aa7Jc
   8:        0x10dc96680 - constellation::Constellation<LTF, STF>::close_pipeline::h14883171717585572041
   9:        0x10dc89fc2 - constellation::Constellation<LTF, STF>::handle_request::h2319527647508186695
  10:        0x10dc7d8bc - constellation::Constellation<LTF, STF>::start::closure.7098
  11:        0x10dc7c008 - thunk::F.Invoke<A, R>::invoke::h7398512893709377427
  12:        0x10dc7acaf - rt::unwind::try::try_fn::h14697338781292147106
  13:        0x10e997928 - rust_try_inner
  14:        0x10e997915 - rust_try
  15:        0x10dc7b4d3 - thunk::F.Invoke<A, R>::invoke::h1803073708590684298
  16:        0x10e984752 - sys::thread::thread_start::hc1f580397175540a22E
  17:     0x7fff901712fb - _pthread_body
  18:     0x7fff90171278 - _pthread_start
thread 'LayoutTask' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:744
stack backtrace:
   1:        0x10e98185d - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10e9958dd - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10e961c19 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10e96209e - rt::unwind::begin_unwind_fmt::hce9ab1c081fbc798S9I
   5:        0x10e99516d - rust_begin_unwind
   6:        0x10e9b7e25 - panicking::panic_fmt::hc7d3b6a3960519fdHZs
   7:        0x10dda1b90 - thunk::F.Invoke<A, R>::invoke::h9970387040411026535
   8:        0x10dd6eb7f - rt::unwind::try::try_fn::h17922520940258702800
   9:        0x10e997928 - rust_try_inner
  10:        0x10e997915 - rust_try
  11:        0x10dd6f3a3 - thunk::F.Invoke<A, R>::invoke::h14138863434235375294
  12:        0x10e984752 - sys::thread::thread_start::hc1f580397175540a22E
  13:     0x7fff901712fb - _pthread_body
  14:     0x7fff90171278 - _pthread_start
thread 'LayoutTaskWatcher' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/larsberg/rust/src/libcore/result.rs:744
stack backtrace:
   1:        0x10e98185d - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10e9958dd - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10e961c19 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10e96209e - rt::unwind::begin_unwind_fmt::hce9ab1c081fbc798S9I
   5:        0x10e99516d - rust_begin_unwind
   6:        0x10e9b7e25 - panicking::panic_fmt::hc7d3b6a3960519fdHZs
   7:        0x10dcf998e - result::Result<T, E>::unwrap::h13059378591360124820
   8:        0x10dda2de8 - thunk::F.Invoke<A, R>::invoke::h3611226144867157275
   9:        0x10dd6eb7f - rt::unwind::try::try_fn::h17922520940258702800
  10:        0x10e997928 - rust_try_inner
  11:        0x10e997915 - rust_try
  12:        0x10dd6f3a3 - thunk::F.Invoke<A, R>::invoke::h14138863434235375294
  13:        0x10e984752 - sys::thread::thread_start::hc1f580397175540a22E
  14:     0x7fff901712fb - _pthread_body
  15:     0x7fff90171278 - _pthread_start
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/larsberg/rust/src/libcore/result.rs:744
stack backtrace:
   1:        0x10e98185d - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10e9958dd - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10e961c19 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10e96209e - rt::unwind::begin_unwind_fmt::hce9ab1c081fbc798S9I
   5:        0x10e99516d - rust_begin_unwind
   6:        0x10e9b7e25 - panicking::panic_fmt::hc7d3b6a3960519fdHZs
   7:        0x10dcaddfe - result::Result<T, E>::unwrap::h11205996779743890143
   8:        0x10dcdfdac - compositor::IOCompositor<Window>.CompositorEventListener::handle_event::h463492030099429797
   9:        0x10dcf18fe - Browser::handle_event::h1f5bb80eb61ba232Xfa
  10:        0x10dc40001 - main::ha4fdb8e9778a1262Faa
  11:        0x10e997928 - rust_try_inner
  12:        0x10e997915 - rust_try
  13:        0x10e996287 - rt::lang_start::ha47b67e90acca8b61mJ
thread 'PaintTask' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:744
stack backtrace:
   1:        0x10e98185d - sys::backtrace::write::h22d7886ea3e34df8JDA
Error running mach:

```
['run', '--release', './servo-shell/index.html', '-e']
```

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'components/servo/target/release/servo', './servo-shell/index.html', '-e']' returned non-zero exit status 101

**Comment by jdm** [comment]
I'm going to re-file this in the servo repo issues, since this should be reproducible in any regular text input field.

**Comment by jdm** [comment]
If you could narrow down what you actually typed, that would be great!

**Comment by bahtou** [comment]
I typed `asdfasdf`

**Comment by pjar** [comment]
I have no url bar on mavericks - is it wrong? :)

**Comment by jdm** [comment]
@pjar If you're following the instructions at https://github.com/glennw/servo-shell/#how-do-i-use-it then you should have a URL bar.

**Comment by dralley** [comment]
If there are no new reports of this, it's old enough to close

**Comment by jdm** [comment]
servo-shell is abandoned. It's not worth triaging things in this repo.
