### ISSUE TITLE
shell not working on fedora 22 (linux)

### ISSUE THREAD

**Issue by EmilyDirsh** [glennw/servo-shell#5]
With builds from servo (https://github.com/servo/servo/commit/db104b738e1ff6b69c3983be6f50f8d7a048b182) and servo-shell (https://github.com/glennw/servo-shell/commit/db419fa3310b6dcd2433e597573103328c66eb5d) browser is non-responsive.

I was unable to get any messages from verbose mode, but by `./mach run http://reddit.com/r/rustlang ../servo-shell/index.html -e` I could at least get a stacktrace.
http://pastebin.com/CCJRxGX9

**Comment by jdm** [comment]
That's just going to run the regular Servo UI on /r/rustlang, and I guess that page triggers a bug in Servo. servo-shell doesn't support providing an initial URL right now.

**Comment by jdm** [comment]
Huh, I lied, apparently that does bring up the servo-shell UI somehow. Spooky.

**Comment by jdm** [comment]
I've filed https://github.com/servo/servo/issues/5520 to remove the ability to make this mistake :)
